name: Build and deploy JAR app to Azure Web App - participacion-ciudadana

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle (skip tests)
        run: ./gradlew clean build -x test --no-daemon

      - name: Verify JAR exists
        run: ls -lh build/libs/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/participacion-ciudadana-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./app   # ⚠️ se descargará aquí

      - name: List downloaded artifacts
        run: ls -lh ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A0D96D27CDD403B8953240BD201390E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C57437E40076459197305C55ABD3B98B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_23A0E4C220C64280B20369563A8E4944 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'participacion-ciudadana'
          slot-name: 'Production'
          package: './app/participacion-ciudadana-0.0.1-SNAPSHOT.jar'